# Numpy Stack

NumPy is the fundamental package for scientific computing with Python and it able to handle a powerful N-dimensional array object.

The central object in Numpy is the Numpy array, on which we can do various operations.

The key is that a Numpy array isn’t just a regular array, but instead is like a mathematical object like a vector or a matrix. That means we can do vector and matrix operations like addition, subtraction, and multiplication.

# Operations

In [0]:
import numpy as np

Initialize L as normal array

In [0]:
L = [1,2,3]

Initialize A as numpy array

In [0]:
A = np.array([1,2,3])

In [4]:
# print out each of the elemnt in L
for e in L:
  print (e)

1
2
3


In [5]:
# print out each of the elemnt in L
for e in A:
  print (e)

1
2
3


Let's try append new number into array L

In [6]:
L.append(4)
L

[1, 2, 3, 4]

It is work fine. Let's try on append numpy array

In [7]:
A.append(4)

AttributeError: ignored

Opps, seem like numpy array not allow to append directly as L

In [0]:
L = L + [5]

In [9]:
L

[1, 2, 3, 4, 5]

In [10]:
A = A + [4,5]

ValueError: ignored

In [11]:
L2 = []
for e in L:
  L2.append(e+e)

L2

[2, 4, 6, 8, 10]

In [12]:
A + A

array([2, 4, 6])

In [13]:
2*A

array([2, 4, 6])

When sum up or multiplication of numpy array, it has no issue. Let's try multiply the L array.

In [14]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Seem like the array extend by double up the length

In [15]:
L2 = []
for e in L:
  L2.append(e*e)

L2

[1, 4, 9, 16, 25]

In [16]:
A**2

array([1, 4, 9])

In [18]:
print("Square root of values in A:")
np.sqrt(A)

Square root of values in A:


array([1.        , 1.41421356, 1.73205081])

In [19]:
print("Square root of values in L:")
np.sqrt(L)

Square root of values in L:


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [20]:
L

[1, 2, 3, 4, 5]

In [21]:
print("Log values in A:")
np.log(A)

Log values in A:


array([0.        , 0.69314718, 1.09861229])

In [22]:
print("Log values in L:")
np.log(L)

Log values in L:


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
print("Exponential values in A:")
np.exp(A)

Exponential values in A:


array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
print("Exponential values in L:")
np.exp(L)

Exponential values in L:


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

# Zip in python

Zip functions is to join two tuples together:

In [25]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a, b)

#use the tuple() function to display a readable version of the result:

print(tuple(x))

(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


If one tuple contains more items, these items are ignored:

In [26]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica", "Vicky")

x = zip(a, b)

#use the tuple() function to display a readable version of the result:

print(tuple(x))


(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


In [0]:
a = np.array([1,2])
b = np.array([2,1])

In [0]:
dot = 0

In [0]:
for e, f in zip(a,b):
  dot += e*f

In [30]:
dot

4

In [31]:
a*b

array([2, 2])

In [32]:
np.sum(a*b)

4

In [33]:
(a*b).sum()

4

In [34]:
np.dot(a,b)

4

In [35]:
a.dot(b)

4

In [36]:
b.dot(a)

4

In [38]:
agm = np.sqrt((a*a).sum())
agm

2.23606797749979

In [0]:
amg = np.linalg.norm(a)

In [40]:
amg

2.23606797749979

In [44]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.7999999999999998

In [0]:
angle = np.arccos(cosangle)

In [46]:
angle

0.6435011087932847

# Speed comparison

In [47]:
from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future


import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 65.1604509090909


# Matrix and Vector

In [0]:
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]

In [49]:
L[0]

[1, 2]

In [50]:
L[0][0]

1

In [51]:
M[0][0]

1

In [0]:
M2 = np.matrix(L)

In [53]:
M2

matrix([[1, 2],
        [3, 4]])

In [0]:
A = np.array(M2)

In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
A.T

array([[1, 3],
       [2, 4]])

# Initialize Metrices

In [57]:
np.array([1,2,3])

array([1, 2, 3])

In [58]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
z = np.zeros((10,10))

In [61]:
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
one = np.ones((10,10))
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
r = np.random.random((10,10))

In [67]:
r

array([[0.29885098, 0.20376018, 0.27309967, 0.61483819, 0.44983985,
        0.54615373, 0.10916485, 0.96048636, 0.01977314, 0.2922642 ],
       [0.08870025, 0.32547313, 0.97215571, 0.4417257 , 0.5695931 ,
        0.39243494, 0.94877104, 0.72154966, 0.61877844, 0.88566723],
       [0.67513005, 0.00915647, 0.64621003, 0.03170277, 0.57446178,
        0.75634598, 0.88438826, 0.83286712, 0.55549121, 0.54348224],
       [0.91602347, 0.87688267, 0.07556213, 0.55013508, 0.65860905,
        0.87047723, 0.50052959, 0.82116386, 0.63333981, 0.89172608],
       [0.11419815, 0.98163037, 0.27859534, 0.01621063, 0.23164452,
        0.26028294, 0.96101131, 0.70548196, 0.73055312, 0.81550041],
       [0.26172325, 0.75683186, 0.23659551, 0.63992367, 0.01222234,
        0.10413971, 0.91605592, 0.26034473, 0.36381233, 0.95477311],
       [0.88366379, 0.4132522 , 0.82023312, 0.81126203, 0.6237857 ,
        0.44119058, 0.4479354 , 0.71841618, 0.04993503, 0.80658834],
       [0.40093006, 0.94016165, 0.8473246

In [0]:
# Return a sample (or samples) from the “standard normal” distribution. 0 to 1
d = np.random.randn(10,10)

In [70]:
d

array([[ 0.868812  , -2.11372714, -1.15428614,  0.17424799, -0.05857704,
        -0.57624531, -0.06122225, -0.41126327, -0.26212762,  0.41671895],
       [ 0.08030281,  1.72641239,  0.4251837 , -0.12972098,  1.72088553,
         0.76085423, -0.34771448, -1.49855993,  1.000024  ,  0.50027552],
       [ 0.74333394, -0.66529939,  0.49036336, -0.35860347, -1.73582554,
         0.16823284, -0.41504058, -1.37960195,  0.34199221, -0.57775215],
       [ 0.31354463, -0.95231472, -0.02235881, -1.28137439,  1.3670647 ,
         1.45315008,  0.81464105, -0.93792517,  0.11746144,  0.45762246],
       [-0.12722148,  0.14418636, -1.92079358,  0.91804612,  0.97555775,
         0.11324708,  0.92940958, -0.85847918,  0.7995935 , -1.43100384],
       [ 1.02405264,  2.28492726, -0.59795725, -0.58266669, -0.35247486,
         0.95405912,  0.7487586 ,  0.17114609,  1.45529709, -1.3854104 ],
       [ 2.13039249,  0.41540209,  1.59980282, -0.20404376, -1.13653698,
        -1.36266823,  1.34238022, -0.10036852

In [71]:
d.mean()

0.12074547240868456

In [72]:
d.var()

1.1683754515399571

# Matrix Products

In [0]:
A = np.array([[1,2],[3,4]])

In [0]:
Ainv = np.linalg.inv(A)

In [75]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [76]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [77]:
A.dot(Ainv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [78]:
np.linalg.det(A)

-2.0000000000000004

In [79]:
np.diag(A)

array([1, 4])

In [80]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [81]:
np.diag([3,5])

array([[3, 0],
       [0, 5]])

In [82]:
a = np.array([1,2])
b = np.array([3,4])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [83]:
np.inner(a,b)

11

In [84]:
a.dot(b)

11

In [85]:
np.diag(A).sum()

5

In [86]:
# Return the sum along diagonals of the array.
np.trace(A)

5

In [87]:
A

array([[1, 2],
       [3, 4]])

In [88]:
X = np.random.randn(100,3)
# Estimate a covariance matrix, given data and weights.
cov = np.cov(X)
cov

array([[ 1.37942234,  0.80159554, -0.72447344, ...,  0.87934829,
        -0.46946152, -0.54312223],
       [ 0.80159554,  0.69703606, -0.20168747, ...,  0.3740813 ,
        -0.47123827, -0.28011039],
       [-0.72447344, -0.20168747,  0.58850815, ..., -0.59169809,
         0.05835292,  0.31892249],
       ...,
       [ 0.87934829,  0.3740813 , -0.59169809, ...,  0.64163754,
        -0.18177125, -0.36725025],
       [-0.46946152, -0.47123827,  0.05835292, ..., -0.18177125,
         0.33006138,  0.15437373],
       [-0.54312223, -0.28011039,  0.31892249, ..., -0.36725025,
         0.15437373,  0.21929578]])

In [89]:
cov.shape

(100, 100)

In [0]:
cov = np.cov(X.T)

In [91]:
cov

array([[0.83493351, 0.17148772, 0.09775487],
       [0.17148772, 0.87622159, 0.02032025],
       [0.09775487, 0.02032025, 1.0064389 ]])

In [92]:
np.linalg.eigh(cov)

(array([0.67162015, 0.94401444, 1.10195941]),
 array([[ 0.76215257,  0.32857436,  0.55781928],
        [-0.6204418 ,  0.61675191,  0.48442652],
        [-0.18486597, -0.71530131,  0.67392032]]))

In [93]:
np.linalg.eig(cov)

(array([0.67162015, 1.10195941, 0.94401444]),
 array([[ 0.76215257, -0.55781928, -0.32857436],
        [-0.6204418 , -0.48442652, -0.61675191],
        [-0.18486597, -0.67392032,  0.71530131]]))

# Solving linear system

In [94]:
A

array([[1, 2],
       [3, 4]])

In [95]:
b

array([3, 4])

In [96]:
b = np.array([1,2])
b

array([1, 2])

In [0]:
x = np.linalg.inv(A).dot(b)

In [98]:
x

array([0. , 0.5])

**It is encourgared to use solve()**

In [0]:
x = np.linalg.solve(A,b)

In [101]:
x

array([0. , 0.5])

# Practice

In [104]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
np.linalg.solve(A,b)

array([1500.,  700.])