# Numpy Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [1]:
[[ 1., 0., 0.],
 [ 0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

# Reshape

In [9]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.shape

(3, 5)

In [12]:
# check the number of axes (dimensions) of the array.
a.ndim

2

In [13]:
a.dtype.name

'int64'

In [14]:
a.itemsize

8

In [15]:
a.size

15

In [16]:
type(a)

numpy.ndarray

In [17]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [18]:
type(b)

numpy.ndarray

# Array Creation

In [19]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [20]:
a.dtype

dtype('int64')

In [21]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [23]:
a = np.array(1,2,3,4)    # WRONG

ValueError: ignored

In [25]:
a = np.array([1,2,3,4])  # correct
a

array([1, 2, 3, 4])

The type of the array can also be explicitly specified at creation time:

In [26]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [28]:
np.empty( (2,3) )  # uninitialized, output may vary

array([[2.7187073e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [29]:
np.arange( 0, 2, 0.3 )  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

# Numpy.take()

numpy.take(array, indices, axis = None, out = None, mode =’raise’) : Return elememts from array along the mentioned axis and indices.

In [31]:
# Python Program illustrating 
# numpy.take method 

import numpy as geek 

#array = geek.arange(10).reshape(2, 5) 
array = [[1, 2, 3, 4, 5], 
		[6, 7, 8, 9, 10]] 
print("Original array : \n", array) 

# indices = [0, 4] 
print("\nTaking Indices\n", geek.take(array, [0, 4])) 

# indices = [0, 4] with axis = 1 
print("\nTaking Indices\n", geek.take(array, [0, 4], axis = 1)) 

Original array : 
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Taking Indices
 [1 5]

Taking Indices
 [[ 1  5]
 [ 6 10]]
