In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(10)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
y

range(0, 10)

In [13]:
list(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

ValueError: ignored

The exception is raised because your X and Y have different number of samples (rows) and train_test_split doesn't like this

In [0]:
X, y = np.arange(20).reshape((10, 2)), range(10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [16]:
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [17]:
X_train

array([[ 0,  1],
       [16, 17],
       [10, 11],
       [18, 19],
       [ 8,  9],
       [ 4,  5],
       [ 2,  3],
       [12, 13]])

In [18]:
X_test

array([[ 6,  7],
       [14, 15]])

In [19]:
 y_train

[0, 8, 5, 9, 4, 2, 1, 6]

In [20]:
y_test

[3, 7]

As we can see, the sample sets were split into 80:20 ratio, 20 is test set. Remember than both X and y should have same number of row.