In [0]:
import numpy as np 

sample = [100, 30, 600, 12, 200]
sample

[100, 30, 600, 12, 200]

In [0]:
np.argmax(sample)

2

It return the position of the highest value

In [0]:
sample2 = [5, 6, 7, 80, 100, 20]
np.argmax(sample2)

4

In [0]:
sample3 = [[5, 6, 80, 100, 20],[100, 30, 600, 12, 200]]
np.argmax(sample3)

7

In [0]:
table1 = np.matrix([[1,2,3],[4,5,6]])
table1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [0]:
table1[:,:]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [0]:
# Call all element until end of 1st row
table1[:1]

matrix([[1, 2, 3]])

In [0]:
# Call all element until end of 2nd row
table1[:2]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [0]:
# first row and 2nd element (included index 0 element)
table1[:1,2]

matrix([[3]])

In [0]:
# to get number '2' and '5' in axis 1 until 2nd row
table1[:2,1]

matrix([[2],
        [5]])

In [0]:
# to get number '3' and '6' in axis 2 until 2nd row
table1[:2,2]

matrix([[3],
        [6]])

In [0]:
A = np.matrix([[1,2,3,33],[4,5,6,66],[7,8,9,99]])
A

matrix([[ 1,  2,  3, 33],
        [ 4,  5,  6, 66],
        [ 7,  8,  9, 99]])

matrix(
<br>[[ 1,  2,  3, 33], ***row 0***
<br>[ 4,  5,  6, 66], ***row 1***
<br>[ 7,  8,  9, 99]]) ***row 2***
<br> *a0 a1 a2 a3*
<br> **a** indicate **axis**

In [0]:
A.shape

(3, 4)

In [0]:
np.argmax(A)  # 11, which is the position of 99

11

In [0]:
np.argmax(A[:,:])  # 11, which is the position of 99

11

In [0]:
# until first row only
np.argmax(A[:1])  # 3, which is the position of 33

3

In [0]:
# until all row in axis 2
np.argmax(A[:,2])  # 2, which is the position of 9

2

In [0]:
# start after first row, but only axis 2, so not included other axis
np.argmax(A[1:,2])  # 1, which is the position of 9

1