`numpy.argsort(a, axis=-1, kind=None, order=None)` <br>
Returns the indices that would sort an array. It works with real/complex arrays containing nan values.

In [0]:
import numpy as np

In [2]:
x = np.array([6, 4, 5])
np.argsort(x)

array([1, 2, 0])

Note that it return the indices, not the values. In the case above, the smallest number is 1 which located at index 1, while the largest is 3 at index 0. Therefore, the sorted indices is from smallest to biggest value.

In [3]:
x = np.array([[10, 11], [12, 13]])
x

array([[10, 11],
       [12, 13]])

In [4]:
sorted_x = np.argsort(x, axis=0)  # sorts along first axis (down)
sorted_x

array([[0, 0],
       [1, 1]])

In [5]:
np.take_along_axis(x, sorted_x, axis=0)  # same as np.sort(x, axis=0)

array([[10, 11],
       [12, 13]])

In [6]:
y = np.array([[12, 11], [10, 13]])
y

array([[12, 11],
       [10, 13]])

In [7]:
sorted_y = np.argsort(y, axis=0)  # sorts along first axis (down)
sorted_y

array([[1, 0],
       [0, 1]])

In [8]:
j = np.array([[12,11,10], [10,11,13], [11,12,13]])
j

array([[12, 11, 10],
       [10, 11, 13],
       [11, 12, 13]])

In [9]:
sorted_j = np.argsort(j, axis=0)  # sorts along first axis (down)
sorted_j

array([[1, 0, 0],
       [2, 1, 1],
       [0, 2, 2]])

In [10]:
sorted_j_first_axis = np.argsort(j, axis=1)  # sorts along first axis (down)
sorted_j_first_axis

array([[2, 1, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [13]:
p = np.array([15, 18, 20])
sorted_p = p.argsort()[-2:][::-1]
sorted_p

array([2, 1])

Let's understand this code 

```
x.argsort()[-j:][::-k]
```



In [14]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[-2:] # return the element from last second

array([ 9, 10])

In [15]:
a[::-1] # reverse the order arrangment

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
a[-2:][::-1]

array([10,  9])

In [21]:
a.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a.argsort()[-10:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a.argsort()[-10:][::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])